<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BuiltInFontsArea>true</BuiltInFontsArea>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.0.10" />
    <PackageReference Include="Avalonia.Desktop" Version="11.0.10" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.0.10" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.0.10" />
    <PackageReference Include="Avalonia.ReactiveUI" Version="11.0.10" />
    <!-- NU1903: Override transitively pulled Tmds.DBus.Protocol to patched version -->
    <PackageReference Include="Tmds.DBus.Protocol" Version="0.21.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MailVault.Domain\MailVault.Domain.csproj" />
    <ProjectReference Include="..\MailVault.Core\MailVault.Core.csproj" />
    <ProjectReference Include="..\MailVault.Indexing\MailVault.Indexing.csproj" />
    <ProjectReference Include="..\MailVault.Validation\MailVault.Validation.csproj" />
    <ProjectReference Include="..\MailVault.Audit\MailVault.Audit.csproj" />
    <ProjectReference Include="..\MailVault.Exporters.Eml\MailVault.Exporters.Eml.csproj" />
    <ProjectReference Include="..\MailVault.Exporters.Mbox\MailVault.Exporters.Mbox.csproj" />
  </ItemGroup>

</Project>
