<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MailVault.Domain\MailVault.Domain.csproj" />
    <ProjectReference Include="..\MailVault.Core\MailVault.Core.csproj" />
    <ProjectReference Include="..\MailVault.Indexing\MailVault.Indexing.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MimeKit" Version="4.16.0" />
  </ItemGroup>

</Project>
